# Generated by Django 4.2 on 2023-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='tone', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='tone', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Tones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(help_text='tone', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(help_text='tool name', max_length=200)),
                ('url', models.CharField(blank=True, help_text='url name', max_length=50)),
                ('url2', models.CharField(help_text='url path', max_length=50)),
                ('description', models.TextField(help_text='description')),
                ('stars', models.IntegerField(help_text='stars')),
                ('image', models.CharField(blank=True, help_text='image', max_length=3000)),
                ('ext', models.BooleanField(default=False)),
            ],
        ),
    ]
